"""
Templar Marketing Website.
A single-page marketing site that showcases templates and links to Gumroad/Payhip listings.

Run locally:
    python -m src.website.app

Render deployment:
    gunicorn -k uvicorn.workers.UvicornWorker src.website.app:app
"""

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse
from fastapi.templating import Jinja2Templates
from fastapi.staticfiles import StaticFiles

# ── App ─────────────────────────────────────────────────────────────────────────

app = FastAPI(title="Templar — AI-Powered Notion Templates", description="Premium Notion templates generated by AI, delivered instantly to your workspace.")

BASE_DIR = Path(__file__).parent
templates = Jinja2Templates(directory=str(BASE_DIR / "templates"))

# Mount static files if they exist
static_dir = BASE_DIR / "static"
if static_dir.exists():
    app.mount("/static", StaticFiles(directory=str(static_dir)), name="static")


# ── Data ─────────────────────────────────────────────────────────────────────

# Template showcase — these match the rule-based templates in notion_template.py
SHOWCASE_TEMPLATES = [
    {
        "slug": "habit-tracker",
        "title": "The Atomic Habits Tracker",
        "tagline": "Build systems, not willpower.",
        "category": "Habit Tracker",
        "price": 19,
        "gumroad_url": "https://gumroad.com/l/templar-habit-tracker",
        "description": "Track daily streaks, weekly reviews, and visual progress. Includes calendar, gallery, and table views. Sample data pre-loaded.",
        "features": ["Streak tracking", "Weekly review system", "Calendar + Gallery views", "Sample data included", "Notion native"],
        "image_class": "habit",
    },
    {
        "slug": "finance-tracker",
        "title": "Clarity — Finance Dashboard",
        "tagline": "Know exactly where every dollar goes.",
        "category": "Finance Tracker",
        "price": 19,
        "gumroad_url": "https://gumroad.com/l/templar-finance-tracker",
        "description": "Track income, expenses, savings goals, and net worth. 5 minutes a week. No bank syncing required — just intentional logging.",
        "features": ["Income + expense logging", "Savings goals", "Net worth tracker", "Monthly reviews", "Zero setup"],
        "image_class": "finance",
    },
    {
        "slug": "project-management",
        "title": "The Minimal PM",
        "tagline": "Everything you need. Nothing you don't.",
        "category": "Project Management",
        "price": 24,
        "gumroad_url": "https://gumroad.com/l/templar-pm",
        "description": "Kanban boards, timeline views, priorities, estimates. Built for solo founders and small teams who hate bloated PM tools.",
        "features": ["Kanban + Timeline", "Priority tracking", "Estimate hours", "Team assignments", "Due date alerts"],
        "image_class": "project",
    },
    {
        "slug": "content-calendar",
        "title": "The Content Engine",
        "tagline": "Consistency without the chaos.",
        "category": "Content Calendar",
        "price": 22,
        "gumroad_url": "https://gumroad.com/l/templar-content-calendar",
        "description": "Plan, schedule, and track content across every platform. Built for creators who want to post consistently without the mental overhead.",
        "features": ["Multi-platform planning", "Status tracking", "Hashtag suggestions", "30-day calendar view", "Caption drafts"],
        "image_class": "content",
    },
    {
        "slug": "student-dashboard",
        "title": "The Dean's List Dashboard",
        "tagline": "Top grades without the stress.",
        "category": "Student Dashboard",
        "price": 17,
        "gumroad_url": "https://gumroad.com/l/templar-student",
        "description": "Assignment tracking, GPA calculation, study time logging, and goal setting — all in one dashboard designed for university students.",
        "features": ["GPA calculator", "Assignment due dates", "Course management", "Study time tracker", "Goal setting"],
        "image_class": "student",
    },
    {
        "slug": "goal-tracker",
        "title": "Goal Crusher",
        "tagline": "Sprints that turn ambitions into achievements.",
        "category": "Goal Tracker",
        "price": 15,
        "gumroad_url": "https://gumroad.com/l/templar-goals",
        "description": "Quarterly sprint system. Break big goals into weekly actions. Track progress visually. No fluff, just results.",
        "features": ["Quarterly sprints", "Weekly action tracking", "Progress visualization", "Celebration system", "Q1–Q4 planning"],
        "image_class": "goal",
    },
]

PRICING_PLANS = [
    {
        "name": "Single Template",
        "price": "From $15",
        "description": "Pick one template. Instant delivery to your Notion workspace.",
        "cta": "Browse Templates",
        "features": ["One template", "Instant Notion delivery", "Setup guide included", "Lifetime updates"],
        "highlighted": False,
    },
    {
        "name": "Bundle (All Templates)",
        "price": "$79",
        "description": "All 6 templates. The complete system. Save 40% vs buying individually.",
        "cta": "Get the Bundle",
        "gumroad_url": "https://gumroad.com/l/templar-bundle",
        "features": ["All 6 templates", "All future templates", "Notion direct delivery", "Priority support"],
        "highlighted": True,
    },
]


# ── Routes ─────────────────────────────────────────────────────────────────────

@app.get("/", response_class=HTMLResponse)
async def home(request: Request):
    return templates.TemplateResponse("index.html", {
        "request": request,
        "templates": SHOWCASE_TEMPLATES,
        "plans": PRICING_PLANS,
    })


@app.get("/templates", response_class=HTMLResponse)
async def all_templates(request: Request):
    return templates.TemplateResponse("templates.html", {
        "request": request,
        "templates": SHOWCASE_TEMPLATES,
    })


@app.get("/template/{slug}", response_class=HTMLResponse)
async def template_detail(request: Request, slug: str):
    tpl = next((t for t in SHOWCASE_TEMPLATES if t["slug"] == slug), None)
    if not tpl:
        from fastapi import HTTPException
        raise HTTPException(status_code=404, detail="Template not found")
    return templates.TemplateResponse("template_detail.html", {
        "request": request,
        "template": tpl,
    })


@app.get("/privacy", response_class=HTMLResponse)
async def privacy(request: Request):
    return templates.TemplateResponse("privacy.html", {"request": request})


@app.get("/terms", response_class=HTMLResponse)
async def terms(request: Request):
    return templates.TemplateResponse("terms.html", {"request": request})


# ── Health check (for Render) ─────────────────────────────────────────────────
@app.get("/health")
async def health():
    return {"status": "ok"}


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", 5000))
    uvicorn.run(app, host="0.0.0.0", port=port)
